#######################################################################
############### DO NOT TOUCH ANYTHING BELOW THIS ######################
#######################################################################

defaults:
  version:
    number: "0.0.0.1" # Do not touch unless doing a release, do not backport the version number that's in master
  heroku: false
  environment:
    url: "http://localhost:3000/"
    certificate_authorities:
    redis:
    require_ssl: true
    single_process_mode: false
    sidekiq:
      concurrency: 5
      retry: 10
      backtrace: 15
      dead_jobs_limit: 5000
      dead_jobs_timeout: 3628800 # 6 weeks
      log: 'log/sidekiq.log'
    s3:
      enable: false
      key:
      secret:
      bucket:
      region:
      cache: true
    image_redirect_url:
    assets:
      serve: false
      upload: false
      host:
    pubsub_server: 'https://pubsubhubbub.appspot.com/'
    logging:
      logrotate:
        enable: true
        days: 7
      debug:
        sql: false
        federation: false
  server:
    listen: 'tcp://0.0.0.0:3000'
    rails_environment: 'development'
    pid: "tmp/pids/web.pid"
    stderr_log:
    stdout_log:
    unicorn_worker: 2
    unicorn_timeout: 90
    embed_sidekiq_worker: false
    sidekiq_workers: 1
  map:
    mapbox:
      enabled: false
      access_token:
      style: "mapbox/streets-v9"
  privacy:
    google_analytics_key:
    piwik:
      enable: false
      host:
      site_id:
    statistics:
      user_counts: false
      post_counts: false
      comment_counts: false
    camo:
      proxy_markdown_images: false
      proxy_opengraph_thumbnails: false
      proxy_remote_pod_images: false
      root:
      key:
  settings:
    pod_name: 'dNext*'
    enable_registrations: true
    enable_local_posts_stream: 'disabled'
    autofollow_on_join: true
    autofollow_on_join_user: 'hq@pod.diaspora.software'
    welcome_message:
      enabled: false
      subject: 'Welcome Message'
      text: 'Hello %{username}, welcome to diaspora*.'
    invitations:
      open: true
      count: 25
    paypal_donations:
      enable: false
      currency: USD
      paypal_hosted_button_id:
      paypal_unhosted_button_encrypted:
    community_spotlight:
      enable: false
      suggest_email:
    typhoeus_verbose: false
    typhoeus_concurrency: 20
    archive_jobs_concurrency: 1
    username_blacklist:
      - 'admin'
      - 'administrator'
      - 'hostmaster'
      - 'info'
      - 'postmaster'
      - 'root'
      - 'ssladmin'
      - 'ssladministrator'
      - 'sslwebmaster'
      - 'sysadmin'
      - 'webmaster'
      - 'support'
      - 'contact'
      - 'example_user'
    terms:
      enable: false
      jurisdiction: false
      minimum_age: false
    maintenance:
      remove_old_users:
        enable: false
        after_days: 730
        warn_days: 30
        limit_removals_to_per_day: 100
    source_url:
    changelog_url:
    default_color_theme: "original"
    default_metas:
      title: 'dNext* social network'
      description: 'dNext* is the online social world where you are in control.'
    csp:
      report_only: false
      report_uri:
  services:
    twitter:
      enable: false
      key:
      secret:
      authorized: true
    tumblr:
      enable: false
      key:
      secret:
      authorized: true
    wordpress:
      enable: false
      key:
      secret:
      authorized: true
  deepl:
    enable: false
  elasticsearch:
    enable_host: false
    enable_cloud: false
  mail:
    enable: false
    sender_address: 'no-reply@example.org'
    method: 'smtp'
    smtp:
      host: 'localhost'
      port: 587
      authentication: 'plain'
      username:
      password:
      starttls_auto: true
      openssl_verify_mode:
      domain:
    sendmail:
      location: '/usr/sbin/sendmail'
      exim_fix: false
    message_bus_api_key:
  admins:
    account:
    podmin_email:

development:
  environment:
    assets:
      serve: true
    single_process_mode: true
    require_ssl: false
    logging:
      debug:
        sql: true
  server:
    unicorn_worker: 1
  settings:
    autofollow_on_join: false
    autofollow_on_join_user: ''
production:
  server:
    listen: 'unix:///tmp/dnext.sock'
test:
  environment:
    url: 'http://localhost:9887/'
    single_process_mode: true
    require_ssl: false
    assets:
      serve: true
  settings:
    autofollow_on_join: false
    autofollow_on_join_user: ''
    invitations:
      open: true
  services:
    twitter:
      enable: true
      key: 'fake'
      secret: 'sdoigjosdfijg'
  mail:
    enable: true
